//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XReceiptService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XReceiptService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Title&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .contactsData
        ///        {
        ///            font-family: Georgia, &apos;Times New Roman&apos;, Times, Sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;background:white;width:700px;font-size:15px;line-height:20px;&quot;&gt;
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&quot;data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGQAAAAnCAYAAAD5Lu2WAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RECEIPT_BODY_1_0_2_0 {
            get {
                return ResourceManager.GetString("RECEIPT_BODY_1_0_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Title&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .contactsData
        ///        {
        ///            font-family: Georgia, &apos;Times New Roman&apos;, Times, Sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;background:white;width:700px;font-size:15px;line-height:20px;&quot;&gt;
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&quot;data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGQAAAAnCAYAAAD5Lu2WAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RECEIPT_BODY_1_0_2_0_C2C {
            get {
                return ResourceManager.GetString("RECEIPT_BODY_1_0_2_0_C2C", resourceCulture);
            }
        }
    }
}
